// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
var services = [
  { title: "IT Consulting", description: "UX-optimised mobile and web-based applications built to fit your requirements, from simple document sharing apps to comprehensive automation systems." },
  { title: "Web Development & Design", description: "Professional web development that attracts the right visitors and guides them toward desired results." },
  { title: "Brand Design & Corporate Identity", description: "Creative and practical branding solutions backed by decades of design experience." },
  { title: "SEO", description: "Search Engine Optimisation that helps your company reach the next level and compete with bigger enterprises." },
  { title: "Social Media Marketing", description: "Data-driven social media campaigns that amplify brand presence across major platforms." },
  { title: "ICT Solutions", description: "A unique methodology to manage and optimise your technology infrastructure for seamless operations." },
  { title: "Mobile App Development", description: "Native and cross-platform mobile applications on iOS and Android." },
  { title: "Data Analytics", description: "Turn data into actionable insights with advanced analytics and visualisation." },
  { title: "Cybersecurity", description: "Vulnerability assessments and complete security implementations to protect your digital assets." },
  { title: "Cloud Solutions", description: "End-to-end cloud migration and management that scales with your business." },
  { title: "Hosting Solutions", description: "Secure, high-performance hosting built for reliability and speed." },
  { title: "Business Growth Through Leveraging IT", description: "Tools and strategies to help your business thrive in a digital-first world." }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the services Athandile Solutions offers, with a short description of each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-partners.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var partners = [
  "Investec",
  "Dynamic DNA",
  "Dynamic Visual Technologies (DVT)",
  "Calus Technologies",
  "Matlalenagri",
  "Mercedes Benz"
];
var list_partners_default = defineTool2({
  name: "list_partners",
  title: "List partners",
  description: "List the partner organisations Athandile Solutions works with.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: partners.join("\n") }],
    structuredContent: { partners }
  })
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var company = {
  name: "Athandile Solutions",
  tagline: "See IT with US",
  summary: "Athandile Solutions is an IT consulting company providing end-to-end web solutions and digital presence for businesses worldwide.",
  website: "https://athandilesolutions.lovable.app",
  pages: ["/", "/about", "/services", "/portfolio", "/careers", "/clients", "/contact"]
};
var get_company_info_default = defineTool3({
  name: "get_company_info",
  title: "Get company info",
  description: "Return basic public information about Athandile Solutions (name, tagline, summary, website, main pages).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(company, null, 2) }],
    structuredContent: company
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "athandile-solutions-mcp",
  title: "Athandile Solutions",
  version: "0.1.0",
  instructions: "Public read-only tools describing Athandile Solutions: the services offered, partner organisations, and general company info.",
  tools: [list_services_default, list_partners_default, get_company_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
